name: Deploy to Prod

on:
  push:
    branches:
      - 'main'

jobs:
  cd-deploy-test:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: setup python
        uses: actions/setup-python@v6.1.0
        with:
          python-version:: 3.11

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Configure CLI
        run: |
          cat <<EOF>> ~/.databrickscfg
          [prod]
          host      = https://adb-7405612008039338.18.azuredatabricks.net/
          azure_client_id = ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id = ${{ secrets.AZURE_TENANT_ID }}
          azure_client_secret = ${{secrets.AZURE_CLIENT_SECRET }}
          EOF

      - name: Deploy to Prod
        run: |
          cd databricks_cityride
          databricks bundle deploy -t prod --profile prod
          
        
        
